// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type User struct {
	ID       string   `json:"id"`
	Name     string   `json:"name"`
	UserType UserType `json:"userType"`
}

type UserInput struct {
	ID       *string  `json:"id"`
	Name     string   `json:"name"`
	UserType UserType `json:"userType"`
}

type UserType string

const (
	// Administrator account
	UserTypeAdmin UserType = "ADMIN"
	// Tutor account
	UserTypeTutor UserType = "TUTOR"
	// Student account
	UserTypeStudent UserType = "STUDENT"
	// Unvalidated Account
	UserTypeUnvalidated UserType = "UNVALIDATED"
	// Suspended Account
	UserTypeSuspended UserType = "SUSPENDED"
	// Retired account
	UserTypeRetired UserType = "RETIRED"
	// Scheduled for deletion
	UserTypeDelete UserType = "DELETE"
)

var AllUserType = []UserType{
	UserTypeAdmin,
	UserTypeTutor,
	UserTypeStudent,
	UserTypeUnvalidated,
	UserTypeSuspended,
	UserTypeRetired,
	UserTypeDelete,
}

func (e UserType) IsValid() bool {
	switch e {
	case UserTypeAdmin, UserTypeTutor, UserTypeStudent, UserTypeUnvalidated, UserTypeSuspended, UserTypeRetired, UserTypeDelete:
		return true
	}
	return false
}

func (e UserType) String() string {
	return string(e)
}

func (e *UserType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserType", str)
	}
	return nil
}

func (e UserType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
